# -*- coding: utf-8 -*-
"""TASK 2  Titanic Data Cleaning & Preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Orp3di8LCLCUztCyvUE_s-9P4Na9FLii
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target
df['species'] = df['species'].map({
    0: 'setosa',
    1: 'versicolor',
    2: 'virginica'
})

print("🔹 Dataset Preview:")
print(df.head())
plt.figure()
df['species'].value_counts().plot(kind='bar')
plt.title("Bar Chart - Count of Each Species")
plt.xlabel("Species")
plt.ylabel("Count")
plt.show()
plt.figure()
df['sepal length (cm)'].plot(kind='hist')
plt.title("Histogram - Sepal Length")
plt.xlabel("Sepal Length")
plt.ylabel("Frequency")
plt.show()
plt.figure()

for species in df['species'].unique():
    subset = df[df['species'] == species]
    plt.scatter(subset['sepal length (cm)'],
                subset['petal length (cm)'],
                label=species)

plt.xlabel("Sepal Length")
plt.ylabel("Petal Length")
plt.title("Scatter Plot - Sepal vs Petal Length")
plt.legend()
plt.show()

